### ISSUE TITLE
Dynamic registration of S3 methods

### ISSUE THREAD

**Issue by krlmlr** [hadley/S3#12]
as in e.g. *hms* might be a good fit for this package: https://github.com/r-spatial/sf/issues/710.

https://github.com/tidyverse/hms/blob/c0cfc010566c6d6fa50e38201b14142a0aea8b29/R/zzz.R#L8-L30

**Comment by hadley** [comment]
Now more clearly belongs in vctrs: https://github.com/r-lib/vctrs/issues/74
