### ISSUE TITLE
sloop::reconstruct() + sticky::sticky() = heart?

### ISSUE THREAD

**Issue by maxheld83** [hadley/S3#13]
Jumping off of https://github.com/hadley/adv-r/issues/1148, attribute retention seems like an important thing.

`sloop::reconstruct()` is a great helper in that regard.

However, it's hard to foresee for users (or, more likely, package developers) for *which* generics (other than, say, `dplyr::mutate()` some `mutate.myClass()` would have to be built. 
You mention in adv-r that e.g. dplyr will do this out of the box at some point (which is fantastic).
However, this is unlikely for base functions such as `subset()` and friends.

It also seems a bit of a duplicate effort to build `mutate.myClassA()` for pkgA and have someone else build `mutate.myClassB()` for pkgB when essentially, all `mutate.xClass()` do the same thing.

I was wondering whether it might therefore make sense to combine sloop::reconstruct with sticky::sticky (or factor this out to a separate package):

1. Offer a separate class (say, `sticky`)  for objects which are supposed to retain their attributes.
   @ctbrown's / @decisionpatterns' [sticky](https://github.com/decisionpatterns/sticky) already does this, though with some limitations.
2. Implement, say, `subset.sticky()` methods the frequently used (base) functions which are unlikely to get such methods from their developers (which would be preferable).
3. Implement a `reconstruct.default()` which pkg developers can fall back on when developing their own `some_function.myClass()`.

I obviously have no business suggesting this and too little understanding of R plumbing for this, but I noticed these two related efforts and thought I'd write this up here.

Would also be happy to chip in, but need some direction.

**Comment by hadley** [comment]
I'm pretty sure this no longer belongs in sloop, see #14 for details.

`sticky()` overlaps somewhat with `vctrs::new_vctr()` which also preserves attributes by default (which is the new principle that we will be applying through out the tidyverse).
