### ISSUE TITLE
Rename to something less confusing

### ISSUE THREAD

**Issue by hadley** [hadley/S3#5]
Maybe essthree or sthree

**Comment by njtierney** [comment]
Just throwing it out there, `sss`

**Comment by hadley** [comment]
I really like sss, but I'm now thinking that it might also need to provide a few helpers for S4, so the name might need to be more generic

**Comment by njtierney** [comment]
Glad you like, but yes, that is a bit tricksy.

some thoughts:

- `shelpers` or `shelp`
- `shandle`
- `shandy`
- `shanks`

**Comment by hadley** [comment]
ssssshim

**Comment by njtierney** [comment]
`shimmy`

**Comment by bgreenwell** [comment]
`sutil` (subtle) utilities for `S3` and `S4` classes

**Comment by mdsumner** [comment]
ssssshim is only funny after reading shelpers, shelp, shandle, shandy and shanks

**Comment by mdsumner** [comment]
now that we're agreed, sssshipit!

**Comment by njtierney** [comment]
Note that `sss` is not available: https://cran.r-project.org/web/packages/sss/

**Comment by njtierney** [comment]
sloop! 😂  Love it.
